### ISSUE TITLE
Usage Information

### ISSUE THREAD

**Issue by jab416171** [Serivy/StreamTheory#11]
Maybe I'm blind but I don't see how to set up a queue. The widget just says "No active queue." How do my followers join a queue? Do I need to make a new one?

**Comment by Serivy** [comment]
Hi @jab416171,

Thanks for trying the extension out!

To create a queue you need to use the widget on the broadcaster dashboard. The widget on the channel screen is only for joining. If you are getting 'no queue' on the dashboard let me know as that sounds like a problem! 

Alternatively you can use the website to create the queue. 
https://twitch.seravy.com

**Comment by jab416171** [comment]
Oh thanks, I didn't even notice there was a way to configure extensions in the dashboard. It may be a good idea to mention that on the extension page, or possibly move that to the "configure" section of the extension.

**Comment by Serivy** [comment]
@jab416171 You're totally right, I will improve the messaging and help. We're going through some pretty big changes so thanks for your valuable feedback!
