### ISSUE TITLE
Flickering panel

### ISSUE THREAD

**Issue by furmanthegerman** [Serivy/StreamTheory#19]
The panel on Twitch flickers back and forth from dark to light theme.  It is super distracting.

Thanks,

FurmanTheGerman

![image](https://user-images.githubusercontent.com/37984274/38176248-b9c32f66-35b9-11e8-8852-6a9575d76a87.png)
![image](https://user-images.githubusercontent.com/37984274/38176251-c2092720-35b9-11e8-90b7-c14a0ccf4e80.png)

**Comment by Serivy** [comment]
Thanks for reporting the bug. Looks like it occurs in conjunction with some other panels.

**Comment by Serivy** [comment]
A fix is in review with twitch. I will close when it is released.

**Comment by Serivy** [comment]
A patch has been pushed to live which should resolve the flickering issue. Re-open the ticket if it is still occurring. Thanks for the report.
