### ISSUE TITLE
Subscribers are not syncing

### ISSUE THREAD

**Issue by MuscleHamster** [Serivy/StreamTheory#20]
How long does it take for Stream Theory to sync with my subs?

**Comment by Serivy** [comment]
It should be syncing every hour and the first time a user connects. I will investigate why your's has not updated and provide a manual override.

**Comment by MuscleHamster** [comment]
Thank you. It is for the account packernation50.

**Comment by MuscleHamster** [comment]
Thank you for your quick and effective fix!
