### ISSUE TITLE
Twitch dashboard extension doesn't load. 

### ISSUE THREAD

**Issue by KeteTRR** [Serivy/StreamTheory#21]
I installed your extension and it shows up on my channel but I cannot configure it. In my Twitch dashboard it just says loading with a spinning circle.

**Comment by Serivy** [comment]
Thanks for letting me know. Sounds like the extension is having trouble talking to the back end. I will run a few tests but could you let me know your twitch username i can see if you were added. 
Also you could try go to https://www.twitch.tv/serivy and see if the queue loads there to make sure it can talk to the backend.

**Comment by KeteTRR** [comment]
Twitch username: TheRunningRiot

Queue loaded on your twitch channel.

Thanks!

**Comment by Serivy** [comment]
Thanks, I have run some checks and there did appear to be an issue. If you could try again and let me know.  If that also does not work you could try logging onto the external site at https://twitch.seravy.com/Queue/Admin

**Comment by KeteTRR** [comment]
It is working now! Thanks for your help!

**Comment by Serivy** [comment]
Not a problem, I will keep an eye on it but if you have it happen again feel free to reopen this issue or make a new one.
