### ISSUE TITLE
Browser window

### ISSUE THREAD

**Issue by TheDestinyGamer1** [Serivy/StreamTheory#23]
I want to pull up the queue in a separate window and whenever I try to it just brings up a page that says "Loading..." and it never changes to the actual queue. Maybe it's my browser or PC that's blocking it but I don't know

**Comment by Serivy** [comment]
Hi,

Are you using the external website to administer the queue or the one on the twitch dashboard?
You should be able to log in and see the admin queue by browsing to [https://twitch.seravy.com/Queue/Admin](https://twitch.seravy.com/Queue/Admin) on a seperate browser window.
"Loading..." would indicate that it's not able to finish retrieving the queue for some reason, as if there is an error getting the queue it will show that error instead.

Let me know if you don't have any luck with using that URL and i will ask some more questions.

Thanks
