### ISSUE TITLE
Unable to create queues from dashboard

### ISSUE THREAD

**Issue by DetectiveFox** [Serivy/StreamTheory#25]
"Create Queue" acts up like a "pointless button"

**Comment by Serivy** [comment]
Hi,

Earlier we had an an issue with the extension back end which may have prevented the action to create the queue. The problem should now be fixed, let me know if creating a queue still does not work for you.

Sorry about the outage!
Thanks

**Comment by Serivy** [comment]
I think this has now been resolved. Let me know if it has not.
