### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by Foo-Dawg** [Serivy/StreamTheory#26]
Hello, Just installed the extension to Twitch. When I go to my live dashboard in twitch the extension panel has been showing an arrow moving in a circle say loading for over 3 hours. I would like to set it up and start using the extension but I am unable to. I tried deactivating and deleting extension and reinstalling it but same issue occurs. How can this issue be fixed? Please advise.

**Comment by Serivy** [comment]
Hi,

It looks like there was an issue with the extension back end with some users preventing log in. The problem should now be fixed, let me know if the extension continues to show as loading.

Sorry about the outage!
Thanks

**Comment by Serivy** [comment]
I think this has now been resolved. Let me know if it has not.
