### ISSUE TITLE
Queue

### ISSUE THREAD

**Issue by HoosonGames** [Serivy/StreamTheory#30]
Doesn't work.  The thing requires I give permission, but there's nothing for me to do so

**Comment by Serivy** [comment]
Hi,

If you could let me know the channel you are having troubles with I can have a look and see what queue is being run. If you are trying to set up your own queue, no permissions are required as it is already granted for your own. Queue control is done via the 'Dashboard' feature of twitch.
![image](https://user-images.githubusercontent.com/9199253/49329667-7972f080-f5bd-11e8-8432-2c992748b251.png)

**Comment by Serivy** [comment]
No follow up.
