### ISSUE TITLE
[BUG] Queue+ Dashboard Widget Not Working

### ISSUE THREAD

**Issue by JosephLCameron** [Serivy/StreamTheory#35]
**Extension**
Queue+

**Describe the bug**
The Queue+ widget located on the Twitch Live Dashboard under Extensions is not loading.

**To Reproduce**
1. Login
2. Go to the Live Dashboard
3. Go to the Extensions area and select Queue+ from the drop down menu

**Expected behavior**
Normally the current queue would display with an options menu. Although I currently have an active queue the widget is blank and has no options for managing the queue.

**Screenshots**
Screenshot attached.
![2019-11-12_08-44-19](https://user-images.githubusercontent.com/6069792/68869396-15124980-06c7-11ea-9108-f4f72f64e29c.jpg)

**Additional context**
You can see that there is an active queue on the Queue+ widget on our Twitch at https://www.twitch.tv/speedrunhypetv

I am receiving this errors in the log:
[Error] XMLHttpRequest cannot load https://twitch.seravy.com/api/twitch/bitqueue/QueueConfig/Get?d=thu%20nov%2014%202019%2010:14:28%20gmt-0500%20(est) due to access control checks.

[Error] Failed to load resource: Preflight response is not successful (Get, line 0)

**Comment by Serivy** [comment]
Thanks for the detailed bug report! This really helps track down the issue.

I have had a quick look at the backend server, I notice right now its under high load so i'm wondering if its falsely flagging DDOS protection. Can you refresh the page after 1 minute and see if you get some controls back? I will take a look at what the back end and see what's going on.

**Comment by JosephLCameron** [comment]
It works now! Thank you

**Comment by Serivy** [comment]
Thanks. I have been keeping an eye on it and I think i can make some improvements. I will keep the ticket open until i perform them.
