### ISSUE TITLE
[BUG] - Queue+ won't load the queue. Possible database issue.

### ISSUE THREAD

**Issue by JosephLCameron** [Serivy/StreamTheory#42]
**Extension**
Queue+ and Channel Feed

**Describe the bug**
The queue will not load. Looks like it can't connect to the database. The backend sits at a loading screen and the channel widget sits at "No Active Queue" but there is definitely a queue.

**To Reproduce**
1. Open Twitch and sign in
2. Go to the creator dashboard
3. Click Queue+ to open the Queue+ panel.

**Expected behavior**
The database of games in the queue usually loads up fine.

**Comment by Serivy** [comment]
Thanks. It appears the backend server was not using the correct cert. This has been fixed and should now be working. Could you double check to see if its working on your end? You may need to close all your browsers down and open it up again.

**Comment by JosephLCameron** [comment]
Everything is working again. Thank you!

**Comment by Serivy** [comment]
Thanks! Without your report it would have been down for longer.

**Comment by JosephLCameron** [comment]
Hi Serivy, It appears the same issue is happening again today. I wasn't sure if I should open a new ticket or not.

**Comment by Serivy** [comment]
Thanks for letting me know, The certification got reset for a different reason this time. I'll change how it gets updated from letsencrypt so this doesn't happen again.
It should be working now if you can confirm.

**Comment by JosephLCameron** [comment]
Yes, everything is working again. Thank you!
