### ISSUE TITLE
Sub Tier

### ISSUE THREAD

**Issue by idanzera** [Serivy/StreamTheory#43]
Username,Subscribe Date,Current Tier,Tenure,Streak,Sub   Type,Founder
--
linkeer_,2020-09-09T23:48:11Z,Tier   1,1,1,gift,false |   |  
raphaelfrazao97,2020-09-09T23:40:09Z,Tier   1,1,1,recurring,true
idanzera,2020-09-09T02:18:12Z,Tier   3,1,1,recurring,false |  
marlonzueiraxd,2020-09-10T01:38:58Z,Tier   1,1,1,gift,false |  
  |   |   |   |   |   |

**Comment by Serivy** [comment]
Unknown ticket.
