### ISSUE TITLE
i dont know why its never working when people want to wait in que

### ISSUE THREAD

**Issue by Novulum** [Serivy/StreamTheory#49]

**Comment by Serivy** [comment]
Hi. I have just double checked and it looks like its still functioning on my test channel. Can you provide your channel name and i can see why I might not be able to queue on your end? Which plugin are you using?

**Comment by Novulum** [comment]
They put the code and it doesnt work. I had to try another extention
hopefully it works. Thank you though 🙏🏻

**Comment by Serivy** [comment]
Hope it works! No worries, thank for trying :)
